  version: '3.8'
  services:
    app:
      build:
        context: .
        dockerfile: Dockerfile
        tags:
          - WebInterpretor:latest
      ports:
        - 8000:8000
      volumes:
        - .:/app
